for i in range(30):
    a = input()
    print(a)
    b = input()
    c = input()
    d = input()
    vazao = float(input().split()[-1])
    justica = float(input().split()[-1])
    efic = float(input().split()[-1])
    over = float(input().split()[-1])
    e = input()
    e = input()
    e = input()

    print(f"{((vazao + justica + efic + over) / 4):.5}")